### PR TITLE
Update for 2024.02 CHERIoT sail

### PR DESCRIPTION
**Pull request by nwf-msr**
Follow along with https://github.com/microsoft/cheriot-sail/pull/35

### CODE REVIEW

**Comment by nwf-msr** [comment]
CI is unlikely to be happy until https://github.com/microsoft/cheriot-sail/pull/35 lands upstream.  The joys of cross-repository coordination.

**Comment by davidchisnall** [comment]
> CI is unlikely to be happy until https://github.com/microsoft/cheriot-sail/pull/35 lands upstream. The joys of cross-repository coordination.

If only we had some system for continuously testing whether integration worked.

**Comment by rmn30** [comment]
@davidchisnall could you click the build button on this again now that https://github.com/microsoft/cheriot-sail/pull/35 is merged?

**Comment by davidchisnall** [comment]
Looks like the important bits pass.  The unhelpful error message is because CI runs from PRs don't get the container registry credentials.  I should fix the CI script to skip those steps for PR runs.

**Comment by davidchisnall** [comment]
#4 is trying to fix the issue with CI.

**Comment by davidchisnall** [comment]
CI passed on the merged version and the new devcontainer is deployed, thanks!

**Pull request merged**
